### ISSUE TITLE
Can't install cheerio do you have an idea ? 

### ISSUE THREAD

**Issue by jungfish** [tommelo/influence#1]
npm install cheerio
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "cheerio"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@types/node"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matthieu/developpement/growth-hacking/influence/npm-debug.log

**Comment by tommelo** [comment]
Hey @jungfish 
It looks like a npm/nodejs installation issue. Can you install any other package(in any other project)?
Try to run ```npm cache clean``` and then try ```npm install``` again.

**Comment by jungfish** [comment]
Hi @tommelo  thanks, I tried it then i installed manually each dependencies request, request composer etc and the only dependency that could not install was cheerio :( 
I haven't seen anything like this on the internet that sucks !

**Comment by tommelo** [comment]
There are some [related issues](https://github.com/npm/npm/issues/14268) in the npm repo, but apparently there's no easy solution for that. My bet is to rebuild the entire nodejs environment.
